# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/xiaomi/toco-misound/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter toco,$(TARGET_DEVICE)),)

endif
